#FROM dpage/pgadmin4:latest
FROM dpage/pgadmin4:8.14

# NOTES about this base image:

# Permissions are too tight to copy wait-for-it.sh so we cannot use that at this time. (There is no chmod on it.)
# There is no specific need to use wait-for-it.sh here has been noted. Everything starts up wvery time with no issues.
# We do use depends_on:

