#FROM bitnami/postgresql:latest
#FROM bitnami/postgresql:17.2.0

# For Bedrock-GIS:
FROM postgis/postgis

# NOTE: postgis/postgis as of May 2025 brings in PostgreSQL 17.5


# Adds extenstions:
# postgis_topology
# postgis_tiger_geocoder


# Enable the extension:
# CREATE EXTENSION postgis;

