FROM postgis/postgis

# NOTE: postgis/postgis as of May 2025 brings in PostgreSQL 17.5

# Adds extenstions:
# postgis_topology
# postgis_tiger_geocoder

# Enable the extension:
# CREATE EXTENSION postgis;

